### ISSUE TITLE
Aborting when calling uv__async_send.

### ISSUE THREAD

**Issue by kevin-xu** [joyent/libuv#1491] opened 2014-09-23 08:17 UTC
When running in Android NDK r8e, we've encountered a bug that results in abnormal termination in the line 199:

libuv//src/unix/async.c

```
169 void uv__async_send(struct uv__async* wa) {
170   const void* buf;
171   ssize_t len;
172   int fd;
173   int r;
174 
175   buf = "";
176   len = 1;
177   fd = wa->wfd;
178 
179 #if defined(__linux__)
180   if (fd == -1) {
181     static const uint64_t val = 1;
182     buf = &val;
183     len = sizeof(val);
184     fd = wa->io_watcher.fd;  /* eventfd */
185   }
186 #endif
187 
188   do
189     r = write(fd, buf, len);
190   while (r == -1 && errno == EINTR);
191 
192   if (r == len)
193     return;
194 
195   if (r == -1)
196     if (errno == EAGAIN || errno == EWOULDBLOCK)
197       return;
198 
199   abort();
200 }
```

errno == EFAULT

If modifying

```
179 #if defined(__linux__)
180   if (fd == -1) {
181     static const uint64_t val = 1;
182     buf = &val;
183     len = sizeof(val);
184     fd = wa->io_watcher.fd;  /* eventfd */
185   }
186 #endif
```

to

```
179 #if defined(__linux__)
180   const uint64_t val = 1;
181   if (fd == -1) {
182     buf = &val;
183     len = sizeof(val);
184     fd = wa->io_watcher.fd;  /* eventfd */
185   }
186 #endif
```

,
then it will be fixed.

Why?

Thanks to you.

Kevin Xu

**Comment by saghul** [comment] 2014-09-23 08:22
I have no idea :-S That code path is executed by all Linux systems, and I never saw such a failure. Does the test suite pass for you? Can you reproduce it outside the Android NDK?

**Comment by kevin-xu** [comment] 2014-09-23 08:32
@saghul thank you :-)

I will run the test suite later.
No, I can't reproduce it outside the Android NDK.

**Comment by kevin-xu** [comment] 2014-09-23 08:33
I'm confused why "static".

**Comment by txdv** [comment] 2014-09-23 08:40
reentrant library all over again.

**Comment by saghul** [comment] 2014-09-23 08:50
> reentrant library all over again.

Not sure what you mean here. That buffer is not touched, it's just written, I don't see any reentrancy problem here.

As for the real problem, according to `man 2 write`, EFAULT can happen when the buffer is outside your addressable space.

**Comment by kevin-xu** [comment] 2014-09-23 08:56
@saghul 
If we add a logging statement in the beginning of the function body, it will not abort.

**Comment by txdv** [comment] 2014-09-23 12:29
> Not sure what you mean here. That buffer is not touched, it's just written, I don't see any reentrancy problem here.

```
199   abort();
```

**Comment by saghul** [comment] 2014-09-23 12:46
Yeah, we could improve that, but that's not the problem. The problem is why write gives a EFAULT error.

**Comment by bnoordhuis** [comment] 2014-09-23 21:38
What does the disassembly for that section look like, before and after?

**Comment by saghul** [comment] 2014-11-26 09:11
No follow-up, closing.

**Closed as completed by saghul** 2014-11-26 09:11 UTC
