### ISSUE TITLE
Windows multiple signals handling bug

### ISSUE THREAD

**Issue by mad-rain** [joyent/libuv#1221] opened 2014-03-30 12:00 UTC
Hi All,

The problem appears only when SIGHUP or SIGINT are registered both.

See piece of code from src/win/signal.c.

Its clear that uv__signal_control_handler_refs must be incremented even it's value is greater than zero. Currently it keeps value as is.

```
static int uv__signal_register_control_handler() {
  /* When this function is called, the uv__signal_lock must be held. */

  /* If the console control handler has already been hooked, just add a */
  /* reference. */
  if (uv__signal_control_handler_refs > 0)
    return 0; <<< Here must be uv__signal_control_handler_refs++ before return

  if (!SetConsoleCtrlHandler(uv__signal_control_handler, TRUE))
    return GetLastError();

  uv__signal_control_handler_refs++;

  return 0;
}
```

Andrew.

**Comment by saghul** [comment] 2014-03-30 12:21
Looks like an issue, yes. Can you open a PR with a patch? A regression test would be great ;-)

**Comment by saghul** [comment] 2014-04-12 08:09
A fix for this landed in https://github.com/joyent/libuv/commit/0c726e76a09efb4b27b0b2ca18b489053c1b50ad

**Closed as completed by saghul** 2014-04-12 08:09 UTC
