### ISSUE TITLE
Test failure OSX 10.6.8

### ISSUE THREAD

**Issue by skaller** [joyent/libuv#1032] opened 2013-12-08 13:41 UTC
# 

`getaddrinfo_fail` failed: timeout
# Output from process `getaddrinfo_fail`: (no output)

[%  76|+ 151|-   1|T   0|S   0]: osx_selectgot some input
with a couple of lines
feel pretty happy

`fs_event_watch_dir` failed: timeout
# Output from process `fs_event_watch_dir`: (no output)

`fs_event_watch_file_current_dir` failed: timeout
# Output from process `fs_event_watch_file_current_dir`: (no output)
# FAIL: test/run-tests

1 of 1 test failed
# Please report to https://github.com/joyent/libuv/issues

make[2]: **\* [check-TESTS] Error 1
make[1]: **\* [check-am] Error 2
make: **\* [check] Error 2

**Comment by skaller** [comment] 2013-12-08 13:42
Oops sorry about the formatting.

**Comment by indutny** [comment] 2013-12-08 18:13
Thanks for reporting this. First failure looks like a result of networking configuration on your computer, perhaps it has no internet at the moment of running the test?

Other ones are just laggy sometimes, may I ask you to try `rm -rf watch_dir watch_file` in a libuv folder and to run tests again after that?

**Comment by ghost** [comment] 2013-12-16 01:13
I can confirm the same issue on OSX 10.9 (with net connectivity, yes)

```
'$ uname -a
Darwin Nathans-MacBook-Air.local 13.0.0 Darwin Kernel Version 13.0.0: Thu Sep 19 22:22:27 PDT 2013; root:xnu-2422.1.72~6/RELEASE_X86_64 x86_64
$ make check
/Library/Developer/CommandLineTools/usr/bin/make  check-am
/Library/Developer/CommandLineTools/usr/bin/make  test/run-tests
make[2]: `test/run-tests' is up to date.
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
[%   0|+   0|-   0|T   0|S   0]: platform_output
Output from process `platform_output`:
uv_get_process_title: /Users/ntaylor/code/libuv/test/.libs/run-tests
uv_resident_set_memory: 565248
uv_uptime: 115170.000000
uv_cpu_info:
  model: Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  speed: 2000
  times.sys: 3681320
  times.user: 3673940
  times.idle: 26108220
  times.irq: 0
  times.nice: 0
  model: Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  speed: 2000
  times.sys: 1054000
  times.user: 1606670
  times.idle: 30801990
  times.irq: 0
  times.nice: 0
  model: Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  speed: 2000
  times.sys: 2048540
  times.user: 2913960
  times.idle: 28500220
  times.irq: 0
  times.nice: 0
  model: Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  speed: 2000
  times.sys: 760820
  times.user: 1329230
  times.idle: 31372540
  times.irq: 0
  times.nice: 0
uv_interface_addresses:
  name: lo0
  internal: 1
  physical address: 00:00:00:00:00:00
  address: ::1
  netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  name: lo0
  internal: 1
  physical address: 00:00:00:00:00:00
  address: 127.0.0.1
  netmask: 255.0.0.0
  name: lo0
  internal: 1
  physical address: 00:00:00:00:00:00
  address: fe80::1
  netmask: ffff:ffff:ffff:ffff::
  name: en0
  internal: 0
  physical address: 7c:d1:c3:df:69:0f
  address: fe80::7ed1:c3ff:fedf:690f
  netmask: ffff:ffff:ffff:ffff::
  name: en0
  internal: 0
  physical address: 7c:d1:c3:df:69:0f
  address: 192.168.1.128
  netmask: 255.255.255.0
=============================================================
[%  76|+ 154|-   0|T   0|S   0]: osx_selectgot some input
with a couple of lines
feel pretty happy
[%  85|+ 173|-   0|T   0|S   0]: fs_event_watch_dir
`fs_event_watch_dir` failed: timeout
Output from process `fs_event_watch_dir`: (no output)
=============================================================
[% 100|+ 201|-   1|T   0|S   0]: Done.
FAIL: test/run-tests
=======================================================
1 of 1 test failed
Please report to https://github.com/joyent/libuv/issues
=======================================================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
    make: *** [check] Error 2'
```

**Comment by chainone** [comment] 2014-01-07 09:00
I have the same issue above on rmbp (10.9.1)

**Comment by saghul** [comment] 2014-01-07 10:17
I cannot reproduce this with 10.8.4. I think that `fs_event_watch_dir` is a bit timing sensitive...

**Comment by skaller** [comment] 2014-01-10 02:03
Sorry for long delay responding, seems I'm associated with my gmail account which I don't actually use .. I have slow (wireless only) internet connectivity at all time.

**Comment by indutny** [comment] 2014-02-14 18:47
Assigning it to me, will look into it sometime later as it is not urgent.

**Comment by saghul** [comment] 2014-07-30 07:09
Same fs event tests fail on 10.9. Closing in favor of https://github.com/joyent/libuv/issues/1263. The cause seems to be a race somewhere.

**Closed as completed by saghul** 2014-07-30 07:09 UTC
