### ISSUE TITLE
1 of 1 test failed

### ISSUE THREAD

**Issue by leijian001** [joyent/libuv#1154] opened 2014-02-26 02:00 UTC
make  check-am
make[1]: 正在进入目录 `/home/electron/libuv'
make  test/run-tests
make[2]: 正在进入目录`/home/electron/libuv'
make[2]: “test/run-tests”是最新的。
make[2]:正在离开目录 `/home/electron/libuv'
make  check-TESTS
make[2]: 正在进入目录`/home/electron/libuv'

Output from process `platform_output`:
uv_get_process_title: /home/electron/libuv/test/.libs/lt-run-tests
uv_resident_set_memory: 737280
uv_uptime: 74902.000000
uv_getrusage:
  user: 0 sec 0 microsec
  system: 0 sec 0 microsec
uv_cpu_info:
  model: Intel(R) Core(TM)2 CPU         T7200  @ 2.00GHz
  speed: 1000
  times.sys: 1226300
  times.user: 4084700
  times.idle: 742192400
  times.irq: 3600
  times.nice: 169200
  model: Intel(R) Core(TM)2 CPU         T7200  @ 2.00GHz
  speed: 1000
  times.sys: 806700
  times.user: 3412000
  times.idle: 744075800
  times.irq: 0
  times.nice: 100100
uv_interface_addresses:
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: 127.0.0.1
  netmask: 255.0.0.0
  name: br-kvm
  internal: 0
  physical address: 00:15:58:c3:6e:bb
  address: 192.168.6.20
  netmask: 255.255.255.0
  name: lo
  internal: 1
  physical address: 00:00:00:00:00:00
  address: ::1
  netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
  name: eth0
  internal: 0
  physical address: 00:15:58:c3:6e:bb
  address: fe80::215:58ff:fec3:6ebb
  netmask: ffff:ffff:ffff:ffff::
  name: br-kvm
  internal: 0
  physical address: 00:15:58:c3:6e:bb
  address: fe80::215:58ff:fec3:6ebb
#   netmask: ffff:ffff:ffff:ffff::

`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
# FAIL: test/run-tests

**Comment by saghul** [comment] 2014-02-26 07:52
Thanks! Although not a bug, this test can fail due to network conditions. Closing.

**Closed as completed by saghul** 2014-02-26 07:52 UTC
