### ISSUE TITLE
osx, make check fails in test-tty on line 99 width > 10

### ISSUE THREAD

**Issue by glycerine** [joyent/libuv#927] opened 2013-09-12 14:48 UTC
OSX 10.6.8 / x86_64

$ git branch -v
- master d7115f0 unix, windows: make uv_is_*() always return 0 or 1
  $

libuv compiles and links fine, but make check fails one test

```
=============================================================
[%   9|+  18|-   0|T   0|S   0]: tty
`tty` failed: exit code 6
Output from process `tty`:
width=0 height=0
Assertion failed in test/test-tty.c on line 99: width > 10
=============================================================
[% 100|+ 194|-   1|T   0|S   0]: Done.
FAIL: test/run-tests
=======================================================
1 of 1 test failed
Please report to https://github.com/joyent/libuv/issues
=======================================================
```

**Comment by bnoordhuis** [comment] 2013-10-17 10:26
Thanks for the bug report.  It's relatively harmless; the kernel is reporting that the tty's dimensions are 0 x 0, basically saying "I don't know."

It seems to be some kind of OS X quirk (at least, I've never seen it happen on other platforms).  Apparently, the XNU kernel sometimes doesn't set the dimensions when you create a new tty.

It's a bit elusive though, I've never been able to reproduce it reliably.  If you know of a way, I'd love to hear it.

**Comment by saghul** [comment] 2014-03-10 20:35
@glycerine any way this can be reproduced? I've never been able to do so in 10.6 or any other OSX for that matter :-S

**Comment by saghul** [comment] 2014-03-29 09:35
No follow up, closing since it couldn't be reproduced.

**Closed as completed by saghul** 2014-03-29 09:35 UTC
Labels: Unix
