### ISSUE TITLE
uv_async_send() not guaranteed to wake up loop on windows

### ISSUE THREAD

**Issue by rogerwang** [joyent/libuv#1453] opened 2014-09-04 08:22 UTC
In uv.h:
`uv_async_send wakes up the event loop and calls the async handle's callback`

But the current implementation on windows uses a flag field `async_sent` to determine whether to post to the IOCP. The flag is reset to 0 in the callback (uv_process_async_wakeup_req). When another thread calls uv_async_send() just after the event loop wakes from polling and before uv_process_async_wakeup_req() get called, the expected wake up action of uv_async_send() will be lost -- the event loop will block in the next iteration.

**Comment by txdv** [comment] 2014-09-04 08:27
Could you provide an example?

The explanation is nice, but a test in the code would make it far more easier to verify the problem in the first problem.

**Comment by saghul** [comment] 2014-09-04 08:44
`uv_async_send` doesn't guarantee that calling the function X times yields X executions of the callback, this is by design.

**Comment by txdv** [comment] 2014-09-04 09:01
O, he meant that. We could actually make that happen in libuv for code consistency between windows and unix? @saghul ?

**Comment by rogerwang** [comment] 2014-09-04 09:02
yes,  but in terms of just wakening the event loop, the current document created an expectation that after the point when a thread calling uv_async_send(), the event loop will wake up, or it will not block on the next iteration, but it does sometimes.

**Comment by saghul** [comment] 2014-09-04 09:03
They are actually consistent. Windows is actually able to make 1 to 1 invocations happen, but it bends backwards to make the same guarantees as Unix does.

**Comment by saghul** [comment] 2014-09-04 09:06
> yes, but in terms of just wakening the event loop, the current document created an expectation that after the point when a thread calling uv_async_send(), the event loop will wake up, or it will not block on the next iteration, but it does sometimes.

We can fix that with documentation, I'll extend this: http://docs.libuv.org/en/latest/async.html#c.uv_async_send but the behavior is correct. Since you are calling the function from another thread you can't possibly know what the loop is doing at that point.

**Comment by saghul** [comment] 2014-09-04 09:15
Updated documentation, it should be regenerated shortly.

**Comment by rogerwang** [comment] 2014-09-04 11:22
Thanks. I found another part of the doc in uv.h is confusing: `the only guarantee is that the callback function is called at least once after the call to async_send`. When there are multiple calls from another thread continuously, it's not obvious which call the document refers to by `the call to async_send` -- the sentence only applies to the very first call, while for the following calls, the callback function may not be called at all.

**Comment by saghul** [comment] 2014-09-04 12:23
@rogerwang can you suggest some text for docs.libuv.org? Whatever is on uv.h will be going away once the API docs are merged.

**Comment by rogerwang** [comment] 2014-09-05 05:57
maybe something like `uv_async_send() is not guaranteed to wake up loop if you have called it previously` -- it's a proper warning.

**Comment by saghul** [comment] 2014-09-05 09:09
Fixed in https://github.com/libuv/api-docs/commit/79d7a432b8ae7d71616c88a32eb884fa22076465

**Closed as completed by saghul** 2014-09-05 09:09 UTC
