### ISSUE TITLE
Specify error handling for uv_write and uv_connect

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#185] opened 2011-09-12 09:25 UTC
uv_write and uv_connect can fail synchronously (returning -1) and asynchronously (reporting result=-1 to the callback). Right now it is unspecified which error will be reported how. 

I think that we should guarantee that errors cause by "external" factors (like a failing network) are reported asynchronously. Only errors that indicate user bugs (EINVAL or ENOTSOCK etc) or serious system errors (ENOMEM etc) should be reported synchronously. I am not sure about errors that are deferred from a failed bind (EADDRNOTVAIL).

opinions?
cc @pietern

**Comment by ry** [comment] 2011-09-12 16:24
Is this not the case right now?

**Comment by pietern** [comment] 2011-09-13 07:38
@piscisaureus That sounds like a solid separation. When `uv_write` only reports `ENOMEM` or `EINVAL`, people using the API can safely put a bunch of asserts there (unrecoverable or programming error), instead of having to check for the "external" conditions as well.

@ry When the write queue is empty, `uv_write` attempts to do the write immediately. When this fails with e.g. a `ECONNRESET`, this is reported back synchronously as well. I had expected this to be reported via the write callback with a -1 status. This is the relevant piece of code: https://github.com/joyent/libuv/blob/3c00d87b4239a6b8358e2085f806170c3eca10cf/src/unix/stream.c#L690-695

I've done some tests that showed that there is little latency difference between calling write directly (and opportunistically) and waiting for the writable event. I did this test on an Ubuntu machine and it could be that the Linux kernel has to do some extra work on the write buffer when write is called directly, because it seemed that this resulted in a bit more latency than waiting for the write event to fire.

**Comment by pietern** [comment] 2011-09-13 10:01
It was a while ago that I did those tests, and did them against the Redis event loop with a lot of hackish code, so set out to reproduce. It appears I was wrong (or my previous test was faulty), and that writing immediately has an advantage (for a small payload, such as `PING\n`).

**Linux (immediate write)**

```
ping_pongs: 31676 roundtrips/s
ping_pongs: 50.0%: 31430ns
ping_pongs: 75.0%: 31584ns
ping_pongs: 90.0%: 31741ns
ping_pongs: 95.0%: 31891ns
ping_pongs: 99.0%: 32478ns
ping_pongs: 99.9%: 45977ns
```

**Linux (write on write event)**

```
ping_pongs: 25472 roundtrips/s
ping_pongs: 50.0%: 39071ns
ping_pongs: 75.0%: 39224ns
ping_pongs: 90.0%: 39385ns
ping_pongs: 95.0%: 39550ns
ping_pongs: 99.0%: 40556ns
ping_pongs: 99.9%: 55023ns
```

This is the code I used to record latency: https://gist.github.com/1213510. The difference is smaller for larger payloads. My new hypothesis is that the advantage of waiting can only be seen when there is a lot of pressure on the write buffer and the immediate writes return `EAGAIN`. Not sure how the advantage could be observed otherwise...

**Comment by bnoordhuis** [comment] 2012-03-15 01:41
Closing, this got fixed.

**Closed as completed by bnoordhuis** 2012-03-15 01:41 UTC
Labels: API

**Comment by piscisaureus** [comment] 2012-03-15 14:47
@bnoordhuis Did it? I am not so sure.

**Comment by bnoordhuis** [comment] 2012-03-15 14:53
No? I don't think it happens with uv-unix anymore but if it's still an issue with uv-win, please reopen.
