### ISSUE TITLE
uv_fs_open fails to open CONIN$ on Windows

### ISSUE THREAD

**Issue by Matt-Esch** [joyent/libuv#1209] opened 2014-03-21 06:33 UTC
Currently, `fs__open` uses `FILE_GENERIC_READ` and `FILE_GENERIC_WRITE` when `O_RDWR` is specified for the read/write access.

``` c
 case _O_RDWR:
    access = FILE_GENERIC_READ | FILE_GENERIC_WRITE;
```

FILE_GENERIC_WRITE and FILE_GENERIC_READ are, as the names suggest, specific to files, and can't be used to open CONIN$. It should be

``` c
  case _O_RDWR:
    access = GENERIC_READ | GENERIC_WRITE;
```

Of course, there is no issue opening `/dev/tty` on unix

See problem: http://stackoverflow.com/questions/22511835/acessing-conin-without-a-tty

**Comment by saghul** [comment] 2014-03-21 08:00
I'm not entirely sure if we can consider this a bug. uv_fs_\* functions are supposed to work for files. For TTYs we have uv_tty_t, maybe the problem can be addressed there?

The fact that it works on Unix doesn't mean it was intended, many things work the same in Unix because "everything is a fd".

**Comment by Matt-Esch** [comment] 2014-03-21 08:44
Using the FILE_GENERIC_READ flag is asserting something special about the fd. I'd say this is going out of your way to assert the type of file that is being accessed. The unix version does no such testing. MSDN docs suggest that the FILE_ cases are not normally to be used anyway.

So I can see how this might go against the intention of the function, but a) no attempt is made on unix to restrict access to "actual files" and b) I don't see any other way for libuv to safely gain access to CONIN$.

**Comment by saghul** [comment] 2014-03-21 09:09
> So I can see how this might go against the intention of the function, but a) no attempt is made on unix to restrict access to "actual files" and b) I don't see any other way for libuv to safely gain access to CONIN$.

Making an attempt on unix would probably mean using `stat`, which would be overkill. As for how to get access to CONIN$, I don't have an answer for that unfortunately. Here is an idea though: for uv_poll_t handles we have 2 init functions: uv_poll_init and uv_poll_init_socket. Maybe we could have something similar on ttys: uv_tty_init and uv_tty_init_handle. On Unix they would be identical, but on Windows the init_handle variant would take HANDLE instead of a fd. Maybe that could work.

/cc @piscisaureus

**Comment by kalderami** [comment] 2014-04-06 11:58
I have a related issue. I am trying to use libuv for communication over a serial line (RS-232). On windows this should also be opened with access GENERIC_READ and or GENERIC_WRITE. However, I actually need to open the device myself on both unix and windows. This is because I need the file handle so I can configure the device and query line states at runtime. On unix this involves calling tcsetattr() and friends, on windows Get/SetCommState() needs to be called. Ideally I would be able to use libuv for streaming read/write and handle the rest manually. I think the filesystem interface might work if there was something like uv_fs_init / uv_fs_init_handle to initialize a uv_fs_t with my existing fd / handle. However, I think the uv stream interface would make more sense if I could use that. The uv_read_start / uv_read_stop seems to fit better for serial communication. Would it make sense to add somethiing like generic streams to libuv? Basically I just want to be able to init a stream with a file descriptor/handle and use uv_read_start, uv_read_stop, and uv_write.

The libuv tty interface appears to be way to focused on console ttys to be useful for serial. For example, on linux it tries to reopen the fd as /dev/tty, on windows it has unwanted console-window related logic. Could a generic UV_FILE stream type make sense?

**Comment by Matt-Esch** [comment] 2014-04-06 12:50
It seems like we want libuv to provide the illusion that the accessible IO is treated equally to a file descriptor. This is a standardization layer. Why should I care how the OS treats the resource? It should just open it.

To me this seems like a problem caused by purposely rejecting anything that isn't a file by using FILE_GENERIC_READ/FILE_GENERIC_WRITE, flags which are not normally used in userland, instead of using GENERIC_READ/GENERIC_WRITE which are intended for userland. There seems to be little argument for making windows specifically strict when linux is loose.

**Comment by saghul** [comment] 2014-04-07 06:06
> Basically I just want to be able to init a stream with a file descriptor/handle and use uv_read_start, uv_read_stop, and uv_write.

Have you tried `uv_pipe_open`?

> The libuv tty interface appears to be way to focused on console ttys to be useful for serial. For example, on linux it tries to reopen the fd as /dev/tty, on windows it has unwanted console-window related logic. Could a generic UV_FILE stream type make sense?

Maybe `uv_tty_t` could be extended to support this, similat to how we do it for `uv_poll_t` handles. I haven't had the time to think it all the way through though.

About a `UV_FILE` stream, IMHO that would be related to operating with regular files, not all types of files / handles.

**Comment by saghul** [comment] 2014-04-07 06:12
> To me this seems like a problem caused by purposely rejecting anything that isn't a file by using FILE_GENERIC_READ/FILE_GENERIC_WRITE, flags which are not normally used in userland, instead of using GENERIC_READ/GENERIC_WRITE which are intended for userland. There seems to be little argument for making windows specifically strict when linux is loose.

Yes, this was on purpose. All `uv_fs_*` functions are meant to deal with regular files. I didn't write that code myself, but my guess is the reason why `uv_fs_open` is loose on unices is to avoid `stat()-ing` the file descriptor. On Windows the limitation is easy, just setting those flags is enough, whereas on Unix we'd need to stat the given path and check the mode. The idea of adding it has crossed my mind several times, as this would avoid abusing `uv_fs_open` and getting deceiving results.

**Comment by saghul** [comment] 2014-08-23 08:18
FWIW, I just noticed we do have a test which opens $conin, but using a tty handle: https://github.com/joyent/libuv/blob/master/test/test-tty.c#L45-L54

**Comment by saghul** [comment] 2014-11-26 08:57
Closing. This should be supported by the new handle proposed in this PR: https://github.com/joyent/libuv/pull/1580

As I mentioned (long time ago), `uv_fs_` are meant to work with regular files.

**Closed as completed by saghul** 2014-11-26 08:57 UTC
