### ISSUE TITLE
uv_setup_args: SEGV accessing envrion[0].

### ISSUE THREAD

**Issue by chobie** [joyent/libuv#477] opened 2012-06-25 14:21 UTC
Hi, I'm playing libuv binding for php personally. (see https://github.com/chobie/php-uv).

I've met SIGSEGV when I call `uv_setup_args` on ubuntu box. 
maybe PHP changed environ variable so this issue was occurred. 

I'm not sure this usage is good. is this expected?

```
<?php
uv_setup_args($_SERVER['argc'], $_SERVER['argv']);
$title = uv_get_process_title();

var_dump($title);
```

```

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff0a03ab5 in uv_setup_args (argc=1, argv=0x7ffff7fccce0) at src/unix/linux/core.c:123
123       for (envc = 0; environ[envc]; envc++);
(gdb) p environ[envc]
Cannot access memory at address 0x0
(gdb) p environ
$1 = (char **) 0x0
(gdb) p envc
$2 = 0
(gdb) p argv
$3 = (char **) 0x7ffff7fccce0
(gdb) p *argv
$4 = 0x7ffff7fc9668 "999-uv_get_process_title.php"
```

libuv version: node-v0.8.0
linux: Linux ubuntu 3.2.0-24-generic #37-Ubuntu SMP Wed Apr 25 08:43:22 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

and I found a article regarding environ.  hope this helpful.

see: https://www.securecoding.cert.org/confluence/display/seccode/ENV31-C.+Do+not+rely+on+an+environment+pointer+following+an+operation+that+may+invalidate+it

Thank you providing cool library :smile:

Shuhei

**Comment by bnoordhuis** [comment] 2012-06-25 15:03
`uv_setup_args()` should be called very early on, e.g. as the first line in main(). By the time PHP code runs, it's almost certainly too late.

I'm going to close this as it's not a bug in libuv.

**Closed as completed by bnoordhuis** 2012-06-25 15:03 UTC

**Comment by chobie** [comment] 2012-06-25 15:09
thank you. I'll put it on early phase.

**Comment by saghul** [comment] 2012-06-25 15:35
In case it helps, I had the same problem on Python and solved it by using a private API to which I gained access with uv_dlsym: https://github.com/saghul/pyuv/blob/master/src/util.c#L187

**Comment by chobie** [comment] 2012-06-25 16:41
@saghul wow, thank you. I'll try to use that function to solve this problem.
