### ISSUE TITLE
Test runner won't run with a shared libuv build

### ISSUE THREAD

**Issue by ghost** [joyent/libuv#1382] opened 2014-07-27 06:00 UTC
I build the libraries with:

```
%build
export CFLAGS="%{optflags}"
export CXXFLAGS="%{optflags}"
%{__python} gyp_uv.py -f make -Dcomponent=shared_library -Duv_library=shared_library
%{__make} %{?_smp_mflags} V=1 -C out BUILDTYPE=Release
...
%check
./out/Release/run-tests
./out/Release/run-benchmarks
```

I get the following error when I run the tests:

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.47xbWs
+ umask 022
+ cd /home/floren/redhat/BUILD
+ cd libuv-0.11.26
+ ./out/Release/run-tests
./out/Release/run-tests: symbol lookup error: ./out/Release/run-tests: undefined symbol: uv_setup_args
```

Let me know please what I'm missing. I tried defining the library path, same error:

```
export LD_LIBRARY_PATH="./out/Release/lib.target"
```

**Comment by saghul** [comment] 2014-07-27 09:44
I could reproduce it on Debian by running:

```
./gyp_uv.py -f make -Dcomponent=shared_library -Duv_library=shared_library
V=1 make -C out BUILDTYPE=Release
./out/Release/run-tests
```

`run-tests` is not linked with libuv it seems:

```
$ ldd ./out/Release/run-tests 
        linux-vdso.so.1 (0x00007fffe55fe000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4321235000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f432102d000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4320d21000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4320a20000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f432080a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f43205ec000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4320243000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4321459000)
```

I think the test runner is not prepared to run with a shared library libuv build ATM.

**Comment by saghul** [comment] 2014-09-04 07:34
Updated the title to refer others here.

**Comment by equalsraf** [comment] 2014-12-05 01:00
Hi, I've bumped into the same issue described in #1451 (duplicate?), Windows MSVC 2013

```
error C2491: '_snprintf' : definition of dllimport function not allowed
```

This particular issue seems to be caused by defining a static snprintf in task.h. A quick (but dirty) workaround is to define it as `__inline`

``` diff
diff --git a/test/task.h b/test/task.h
index e890c77..2c05629 100644
--- a/test/task.h
+++ b/test/task.h
@@ -188,7 +188,7 @@ enum test_status {
 /* Emulate snprintf() on Windows, _snprintf() doesn't zero-terminate the buffer
  * on overflow...
  */
-static int snprintf(char* buf, size_t len, const char* fmt, ...) {
+__inline int snprintf(char* buf, size_t len, const char* fmt, ...) {
   va_list ap;
   int n;
```

Then I get the following errors

```
test-spawn.obj : error LNK2019: unresolved external symbol _make_program_args referenced in function _run_test_argument_escaping
test-spawn.obj : error LNK2019: unresolved external symbol _quote_cmd_arg referenced in function _run_test_argument_escaping
test-spawn.obj : error LNK2019: unresolved external symbol _make_program_env referenced in function _run_test_environment_creation
```

These would come from libuv, but since it a shared lib they cannot be used. Just as an example, an equally dirty fix is add dllexport to those functions, i.e.

``` diff
diff --git a/src/win/process.c b/src/win/process.c
index 4d04a0e..d56e4b6 100644
--- a/src/win/process.c
+++ b/src/win/process.c
@@ -445,6 +445,7 @@ static WCHAR* search_path(const WCHAR *file,
  * Quotes command line arguments
  * Returns a pointer to the end (next char to be written) of the buffer
  */
+__declspec(dllexport)
 WCHAR* quote_cmd_arg(const WCHAR *source, WCHAR *target) {
   size_t len = wcslen(source);
   size_t i;
@@ -517,7 +518,7 @@ WCHAR* quote_cmd_arg(const WCHAR *source, WCHAR *target) {
   return target;
 }

-
+__declspec(dllexport)
 int make_program_args(char** args, int verbatim_arguments, WCHAR** dst_ptr) {
   char** arg;
   WCHAR* dst = NULL;
@@ -674,6 +675,7 @@ static int qsort_wcscmp(const void *a, const void *b) {
  * https://github.com/Alexpux/Cygwin/blob/b266b04fbbd3a595f02ea149e4306d3ab9b1fe3d/winsup/cygwin/environ.cc#L955
  *
  */
+__declspec(dllexport)
 int make_program_env(char* env_block[], WCHAR** dst_ptr) {
   WCHAR* dst;
   WCHAR* ptr;
```

Looking at make_program_args, quote_cmd_arg, make_program_env and snprintf - these seem to be independent functions, that could be moved into a separate .c file (shared between libuv and run-tests), instead of trying to access the symbols over a shared library.

**Comment by equalsraf** [comment] 2014-12-05 01:57
Now for the Linux part of this bug, I was able to replicate as described. As in windows it seems to be a problem with accessing symbols from the shared library, but in fact it is a different issue altogether

First look at the linked libraries for the run-tests executable:

```
$ ldd run-tests
        linux-vdso.so.1 (0x00007fffd5fa4000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f17321c2000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f1731fba000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f1731cb2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f17319af000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1731798000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f173157a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f17311cc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f17323c6000)
```

libuv is nowhere to be found, it makes sense that LD_LIBRARY_PATH fails to fix the issue, the linker cannot load a library that it does not know is needed. Again dirty hack just for demonstration purposes

```
LD_PRELOAD=lib.target/libuv.so ./run-tests
```

This works as intended for me.

The build command for run-tests is ([here in full](https://gist.github.com/equalsraf/2778ff694a2e4d4a929b))

```
g++ -pthread -pthread -Wl,-rpath=\$ORIGIN/lib.target/ 
-Wl,-rpath-link=\/home/raf/Documents/src/libuv/out/Debug/lib.target/  
-o /home/raf/Documents/src/libuv/out/Debug/run-tests -Wl,--start-group  
[LOTS OF OBJECT FILES]
/home/raf/Documents/src/libuv/out/Debug/obj.target/libuv.so -Wl,--end-group 
-lm -Wl,-soname,libuv.so.1.0 -ldl -lrt
```

By removing the reference to libuv.so from the command and adding  `-luv -LDebug/lib.target/`at the end I was able to build a run-tests binary that showed the missing entry in ldd. However it is still not working properly because

```
$ ldd Debug/run-tests
        (...)
        libuv.so.1.0 => not found
        (...)
```

that entry points to libuv.so.1.0, but the actual .so file that was built in lib.target/ does not have the so.version in the name - even setting LD_LIBRARY_PATH will not help. I don't have a fix for this since this is my first time using gyp, but hopefully this helps someone track it.

**Comment by saghul** [comment] 2015-04-30 08:12
This was fixed for Unix in https://github.com/libuv/libuv/pull/329. Windows still needs some work, which should happen over at libuv/libuv.

**Closed as completed by saghul** 2015-04-30 08:12 UTC
