### ISSUE TITLE
spawn_setuid_setgid failing test

### ISSUE THREAD

**Issue by dariocravero** [joyent/libuv#1172] opened 2014-03-02 11:10 UTC
@saghul sorted it out one of the failing tests in #1161. However, one test is still failing from that set, see [this](https://gist.github.com/dariocravero/9250901#file-libuv-compilation-error-L638):

```
=============================================================
[%  74|+ 159|-   0|T   0|S   0]: spawn_setuid_setgid
`spawn_setuid_setgid` failed: exit code 134
Output from process `spawn_setuid_setgid`:
Assertion failed in test/test-spawn.c on line 925: r == 0
=============================================================
```

Is that of any importance too?
Thanks,
Darío

**Comment by saghul** [comment] 2014-03-02 11:12
Are you running the tests as root or as another user? I ran the test suite on my BBB yesterday and all tests passed :-)

**Comment by dariocravero** [comment] 2014-03-02 11:20
Just run them again from the latest code on the repo and got the same. I'm running them as root. Should I try as a regular user?

**Comment by saghul** [comment] 2014-03-02 11:55
I tried it that way as well. I'll try again later, maybe I just got lucky.

**Comment by saghul** [comment] 2014-03-03 08:59
I ran the test suite on my BBB again, with Armstrong and with Debian, and couldn't reproduce it with either :-/

**Comment by saghul** [comment] 2014-03-29 09:36
Not Jenkins nor myself using the same environment as the OP were able to reproduce it, closing.

**Closed as completed by saghul** 2014-03-29 09:36 UTC
