### ISSUE TITLE
uv_run_once() should return immediately on a timer with zero timeout

### ISSUE THREAD

**Issue by rogerwang** [joyent/libuv#574] opened 2012-10-04 14:46 UTC
the following code should return immediately but it doesn't:

  r = uv_timer_init(uv_default_loop(), &once);
  r = uv_timer_init(uv_default_loop(), &never);
  r = uv_timer_start(&never, never_cb, 86400 \* 1000, 0);
  r = uv_timer_start(&once, once_null_cb, 0, 0);
  r = uv_run_once(uv_default_loop());

the loop calls once_null_cb() immediately but then waits for the next timer.

**Comment by rogerwang** [comment] 2012-10-04 14:47
the same thing happens if the timer is small enough. e.g. <5ms

**Comment by txdv** [comment] 2012-10-04 16:12
use async_t if you want to emulate NO_WAIT.

**Comment by rogerwang** [comment] 2012-10-04 23:38
How? I'd like to implement something like uv_run_once(loop, max_wait_time).

**Comment by saghul** [comment] 2012-10-04 23:48
You may want to check this out: https://github.com/joyent/libuv/pull/561

**Comment by rogerwang** [comment] 2012-10-04 23:53
Thanks. I'll wait for that API to be implemented on all the platforms.

Currently I'm sending a async event in the timer callback to make sure the loop will be wake up, but that is a side effect.

**Comment by piscisaureus** [comment] 2012-10-04 23:54
@rogerwang We will have this, some day :-)

You cal also prevent the loop from blocking by starting an uv_idle handle with a dummy callback. That should be more efficient than using an uv_async handle.

**Comment by bnoordhuis** [comment] 2012-10-05 03:06
I can confirm the bug. It works when you close the zero timeout handle in its callback but if you leave it open (open but inactive), the event loop stalls.

**Comment by deanm** [comment] 2012-12-21 15:44
Just want to comment that runloop integration is something I've tackled a few times for Plask.  I've just recently rewritten it for libuv and taken a new approach (that is kqueue specific).  There are at least some helpful comments that explain the approach and might be helpful:

https://github.com/deanm/plask/commit/3db9c663adb1d24bc07e523614fef8e4167cdbc3

**Comment by bnoordhuis** [comment] 2013-05-29 22:27
Fixed in 0017c55.

**Closed as completed by bnoordhuis** 2013-05-29 22:27 UTC

**Comment by piscisaureus** [comment] 2013-05-29 22:28
ho! stop! not in v0.10!

**Comment by piscisaureus** [comment] 2013-05-29 22:30
It won't work in v0.10 because ffe2ef06eba7c65deea57c5c27c085c51b989dd4 is only in master and can't be landed in v0.10.

**Comment by bnoordhuis** [comment] 2013-05-29 22:34
Belay that, landed in master only in commit f6d8ba3.

**Comment by piscisaureus** [comment] 2013-05-29 22:36
People who really rely on this bug fixed in v0.10 should float  ffe2ef0 and f6d8ba3. We can't do that because it changes the ABI.
