### ISSUE TITLE
Build errors on Windows

### ISSUE THREAD

**Issue by schlamar** [joyent/libuv#732] opened 2013-03-04 15:20 UTC
Any ideas for these errors:

```
libuv.lib(util.obj) : error LNK2019: unresolved external symbol _imp__RegQuery    
    ValueExW@24 referenced in function _uv_uptime [libuv\run-benchmarks.vcxproj]
libuv.lib(util.obj) : error LNK2019: unresolved external symbol __imp__RegCloseKey@4 
    referenced in function _uv_cpu_info [libuv\run-benchmarks.vcxproj]
libuv.lib(util.obj) : error LNK2019: unresolved external symbol __imp__RegOpenKeyExW@20 
    referenced in function _uv_cpu_info [libuv\run-benchmarks.vcxproj]
libuv\Debug\run-benchmarks.exe : fatal error LNK1120: 3 unresolved externals [libuv\run-benchmarks.vcxproj]

test-spawn.obj : error LNK2019: unresolved external symbol __imp__CommandLineToArgvW@8 
    referenced in function _run_test_argument_escaping [libuv\run-tests.vcxproj]
libuv.lib(util.obj) : error LNK2019: unresolved external symbol __imp__RegQueryValueExW@24 
    referenced in function _uv_uptime [libuv\run-tests.vcxproj]
libuv.lib(util.obj) : error LNK2019: unresolved external symbol __imp__RegCloseKey@4 
    referenced in function _uv_cpu_info [libuv\run-tests.vcxproj]
libuv.lib(util.obj) : error LNK2019: unresolved external symbol __imp__RegOpenKeyExW@20 
    referenced in function _uv_cpu_info [libuv\run-tests.vcxproj]
libuv\Debug\run-tests.exe : fatal
error LNK1120: 4 unresolved externals [C:\Users\schlaich\Documents\GitHub\pyuv\
deps\libuv\run-tests.vcxproj]
```

**Comment by bnoordhuis** [comment] 2013-03-04 15:28
Duplicate of #728.

**Closed as completed by bnoordhuis** 2013-03-04 15:28 UTC
