### ISSUE TITLE
../deps/uv/src/unix/core.c:701: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

### ISSUE THREAD

**Issue by jwolski** [joyent/libuv#1348] opened 2014-07-02 04:36 UTC
We are seeing intermittent failures with node v0.10.26 on Ubuntu 12.04.4 with the following error:

```
../deps/uv/src/unix/core.c:701: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
```

node-ldap is not in use in this application as referenced in #838.

**Comment by saghul** [comment] 2014-07-02 07:31
Can you provide a reduced (ie, no dependencies) test case? Are you using any binary addons?

**Comment by saghul** [comment] 2014-07-06 18:56
Ping.

**Comment by jwolski** [comment] 2014-07-15 18:16
@saghul It's going to take us some time before we can have a test case because as of now we have very little information about why it's occurring. We are using some binary addons. I'll provide a list shortly...

**Comment by sh1mmer** [comment] 2014-07-15 18:56
These are all of the node_modules in the tree with a build folder.

bignum@0.6.1
bignum@0.6.2
dtrace-provider@0.2.8
ffi@1.2.6
hiredis@0.1.15
isarray@0.0.1
libxmljs@10.8.1
libxmljs@10.9.0
nan@1.2.0
ref@20.3.2
sinon@1.4.0
source-map@0.1.37
toobusy@0.2.4
zookeeper@3.4.5-1
zookeeper@3.4.5-2

**Comment by saghul** [comment] 2014-07-15 20:52
Sorry, but I can't possibly debug the issue like this :-S If you can make a node core-only test case I might be able to, best would be a libuv C test case.

FWIW, you could begin by looking into binary addons that use uv handles, specially uv_poll_t handles.

**Comment by sh1mmer** [comment] 2014-07-16 02:40
I just did a quick check. None of these modules use `uv_poll_t`

**Comment by saghul** [comment] 2014-07-16 06:01
That will make it even harder to find :-(

**Comment by saghul** [comment] 2014-08-09 09:48
Closing, please feel free to reopen if you find a way to reproduce it.

**Closed as completed by saghul** 2014-08-09 09:48 UTC

**Comment by tkelman** [comment] 2014-08-09 14:40
We've been seeing this same assertion failure with the Julia fork (see https://github.com/JuliaLang/julia/issues/7840), but it's intermittent and we haven't pinned it down yet. Will be sure to report if we ever do figure out what's causing it.

**Comment by saghul** [comment] 2014-08-09 14:59
That would be great!

**Comment by Tharit** [comment] 2014-08-21 14:01
I'm seeing the same error with node v0.10.30; appears very infrequently and I have not been able to reproduce it. affected application is an http server that makes heavy use of canvas and mariasql modules, everything else is js.

**Comment by mdlavin** [comment] 2014-10-16 21:47
For what it's worth, I've seen the same failure when I use ZooKeeper in certain situations.  Your list of dependencies includes zookeeper which should include the same problem I'm seeing.  I'm not sure if you are seeing the exact same problem as me, but I've submitted a pull request that addresses my issues:  yfinkelstein/node-zookeeper#101

**Comment by saghul** [comment] 2014-10-16 22:01
@mdlavin I haven't looked in the node-zookeeper code, but your reasoning in the issue is correct! :cake:

**Comment by rafahoro** [comment] 2014-11-19 18:23
I have the same issue in my code. It solved after commenting the a line to create a pipe with child's stdin (the code below was in my code, not in a library, but may help you finding the problematic line):

``` javascript
var cp = spawn(SPAWN_BIN, SPAWN_ARGS, {"env": env});
cp.stdout.pipe(process.stdout);
cp.stderr.pipe(process.stderr);
// https://github.com/Unitech/PM2/issues/659
// process.stdin.pipe is causing the following error when using PM2
//node: ../deps/uv/src/unix/core.c:701: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
//process.stdin.pipe(cp.stdin);
```
