### ISSUE TITLE
uv_pipe_bind allows multiple binds to same pipe

### ISSUE THREAD

**Issue by erickt** [joyent/libuv#158] opened 2011-08-29 22:05 UTC
uv_pipe_bind used to use flock to protect against rebinding a unix domain socket, but that code was removed in b2ed24d because flock is not supported on Solaris. This has broken the test `test-pipe-bind-error.c` on darwin with this error:

`pipe_bind_error_addrinuse` failed: exit code 6
Output from process `pipe_bind_error_addrinuse`:
Assertion failed in test/test-pipe-bind-error.c on line 58: r == -1

**Comment by bnoordhuis** [comment] 2011-08-30 17:00
Yes, and it's making me sad. :`(

`flock()` doesn't exist on sunos and `lockf()` and `fcntl()` have nasty semantics. I cry a little every time I run `make test` but I don't know of a good way to solve it.

Node 0.4.x solves it by stat'ing and unlinking the socket but that's so race-y, I don't want to consider it.

**Comment by bacchusrx** [comment] 2011-12-19 03:58
I forked libuv and reimplemented this against the lastest master. See:

https://github.com/bacchusrx/libuv/compare/master...pipe-flock

`test-pipe-bind-error.c` passes there. 

I needed this behaviour for a project I'm working on and I don't use Solaris so this is good enough for me. Maybe it'll be helpful to others until a more universal, official fix is adopted.

**Comment by Marak** [comment] 2012-03-14 04:31
Is there any status on this? This seems like something that should be available to Node.js

**Comment by bacchusrx** [comment] 2012-03-14 04:37
I don't know if it would be acceptable to #ifdef around sunos so that this works at least on Linux, Darwin, etc., for now. It doesn't feel right, but at least it wouldn't be broken everywhere.

**Comment by bnoordhuis** [comment] 2012-03-15 00:53
Duplicate of #135. I don't think we can fix this using traditional methods (at least in a portable way) but who knows.

EDIT: Make that #124.

**Closed as completed by bnoordhuis** 2012-03-15 00:53 UTC
Labels: Unix, pipes
