### ISSUE TITLE
Assertion error in uv__udp_finish_close()

### ISSUE THREAD

**Issue by anolivetree** [joyent/libuv#1406] opened 2014-08-08 04:09 UTC
I'm using libuv-v0.11.25 on Android. I got the following assertion error.

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
Abort message: '../src/unix/udp.c:65: uv__udp_finish_close: assertion "!uv__io_active(&handle->io_watcher, UV__POLLIN | UV__POLLOUT)" failed'

Soruce code of udp.c is following.
 61 void uv__udp_finish_close(uv_udp_t\* handle) {
 62   uv_udp_send_t\* req;
 63   QUEUE\* q;
 64 
 65   assert(!uv__io_active(&handle->io_watcher, UV__POLLIN | UV__POLLOUT));
 66   assert(handle->io_watcher.fd == -1);
 67

**Comment by saghul** [comment] 2014-08-08 07:37
Do you have any test that reproduces this failure?

**Comment by anolivetree** [comment] 2014-08-08 09:36
I'm afraid not. It's a big program and the crash has happened only once so far.

**Comment by saghul** [comment] 2014-11-26 09:09
No follow-up, cannot reproduce, closing. If you manage to reliably reproduce it, please reopen at libuv/libuv, we moved the development there.

**Closed as completed by saghul** 2014-11-26 09:09 UTC
