### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by roselyndomingo** [joyent/libuv#1471] opened 2014-09-12 02:54 UTC
I cloned libuv from https://github.com/joyent/libuv, there's a problem with building it in Ubuntu:

OK    -    $ sh autogen.sh
OK    -    $ ./configure
OK    -    $ make
NG    -    $ make check
         -    $ make install
# Following is the error i got in "make check":

`spawn_setuid_setgid` failed: exit code 6
Output from process `spawn_setuid_setgid`:
# Assertion failed in test/test-spawn.c on line 1054: r == 0
# FAIL: test/run-tests

1 of 1 test failed
# Please report to https://github.com/joyent/libuv/issues

make[2]: **\* [check-TESTS] Error 1
make[2]: Leaving directory `/root/libraries/libuv_git/libuv'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory`/root/libraries/libuv_git/libuv'
make: **\* [check] Error 2

**Comment by saghul** [comment] 2014-09-12 07:22
Duplicate of https://github.com/joyent/libuv/issues/1339. Please search for related issues before reporting.

**Closed as completed by saghul** 2014-09-12 07:22 UTC
