### ISSUE TITLE
linux:threadpool thread race

### ISSUE THREAD

**Issue by richmonkey** [joyent/libuv#628] opened 2012-11-22 06:09 UTC
When run to 
uv_async_send(&w->loop->wq_async);   in function thread_pool.c:work
variable w may be destroyed by other thread that run the fs callback
Because the main thread is running in uv__work_done and not be waked by uv_async_send
Is it true?

**Comment by txdv** [comment] 2012-11-22 11:03
example or it didn't happen

**Comment by indutny** [comment] 2012-11-22 11:05
Is it a question or a bug?

**Comment by richmonkey** [comment] 2012-11-22 12:33
A bug 
Thread race condition can't be reproduced when  low throughput.
Before uv_mutex_unlock,  i save w->loop in a local variable, no segment fault happen

**Comment by indutny** [comment] 2012-11-22 12:35
Can you please provide a test case, or just show code that reproduces this problem.

**Comment by richmonkey** [comment] 2012-11-22 14:06
Sorry 
The issue reproduce depend on the system's process dispatch and the main thread load.
I can't provide a simple test case.

But adding some time sleep in worker and uv__work_done will makes reproduce easy

**Comment by richmonkey** [comment] 2012-11-22 14:07
function:worker
uv_mutex_lock(&w->loop->wq_mutex);
ngx_queue_insert_tail(&w->loop->wq, &w->wq);
uv_mutex_unlock(&w->loop->wq_mutex);
sleep(10)/_second_/
uv_async_send(&w->loop->wq_async);

main thread:
callback() {
free(uv_fs_t);
}
malloc(uv_fs_t)
fs_read(callback)

sleep(5)
malloc(uv_fs_t)
fs_read(callback)

run_loop() 

Wating 5s uv__work_done will be called 
At this point loop's wq has two items then two uv_fs_t is destroyed
After 5s  uv_async_send access the memory of second uv_fs_t

**Comment by indutny** [comment] 2012-11-22 14:10
Well, I can't see where you're allocating/opening and closing `wq_async`. It seems to be the most important thing to check.

**Comment by bnoordhuis** [comment] 2012-11-22 14:12
I agree it's a bug. Does bnoordhuis/libuv@dcd3b55 fix it?

**Comment by richmonkey** [comment] 2012-11-22 14:41
Yes.
Save w->loop in a local variable before uv_mutex_unlock can  fix it  too

**Closed as completed** 2012-11-22 14:42 UTC

**Comment by bnoordhuis** [comment] 2012-11-22 15:24
Fixed in dcd3b55.  Saving the pointer isn't necessarily safe, the loop may have been destroyed if that work_req was the last one.
