### ISSUE TITLE
Reoccurring segfaults in uv__req_unregister

### ISSUE THREAD

**Issue by kkoopa** [joyent/libuv#1041] opened 2013-12-12 20:04 UTC
Running an application with Node.js 0.11.9 and several addons produces hard-to-reproduce but frequent segfaults in the same location.

``` bash
Program terminated with signal 11, Segmentation fault.
#0  0x000000000073202d in uv__write_callbacks (stream=0x2b1b100) at ../deps/uv/src/unix/stream.c:883
883         uv__req_unregister(stream->loop, req);
(gdb) bt
#0  0x000000000073202d in uv__write_callbacks (stream=0x2b1b100) at ../deps/uv/src/unix/stream.c:883
#1  uv__stream_io (loop=<optimized out>, w=0x2b1b170, events=<optimized out>) at ../deps/uv/src/unix/stream.c:1161
#2  0x000000000072a2cb in uv__run_pending (loop=0x10233e0) at ../deps/uv/src/unix/core.c:627
#3  uv_run (loop=0x10233e0, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:270
#4  0x00000000005c81ec in node::Start(int, char**) ()
#5  0x00007fe32ad9b76d in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00000000005b8489 in _start ()
(gdb) print req
$1 = (uv_write_t *) 0x2b1b180
(gdb) print *req
$2 = {data = 0x2b1b178, type = 45199752, active_queue = {0x2b1b188, 0x100000001}, cb = 0xc, send_handle = 0x2b1b1a8, handle = 0x2b1b1a8, queue = {0x2b1b1b8, 0x2b1b1b8}, write_index = 0, bufs = 0xffffffff00000000, nbufs = 193, error = 0, bufsml = {{base = 0x0, len = 0},
    {base = 0x0, len = 4607182418800017408}, {base = 0x0, len = 0}, {base = 0x0, len = 4607182418800017408}}}
(gdb) print *loop
No symbol "loop" in current context.
(gdb) print stream->loop
$3 = (uv_loop_t *) 0x10233e0
(gdb) print *stream->loop
$4 = {data = 0x0, active_handles = 28, handle_queue = {0x1023600, 0x2b2d640}, active_reqs = {0x2b520, 0x2ac8238}, stop_flag = 0, flags = 0, backend_fd = 6, pending_queue = {0x1023428, 0x1023428}, watcher_queue = {0x1023438, 0x1023438}, watchers = 0x2b44a20,
  nwatchers = 62, nfds = 23, wq = {0x1023458, 0x1023458}, wq_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, wq_async = {
    close_cb = 0, data = 0x0, loop = 0x10233e0, type = UV_ASYNC, handle_queue = {0x101f6e0, 0x1023600}, flags = 49152, next_closing = 0x0, async_cb = 0x7344c0 <uv__work_done>, queue = {0x101f708, 0x1023538}, pending = 0}, closing_handles = 0x2b2d620, process_handles = {
    {0x10234f8, 0x10234f8}}, prepare_handles = {0x1023508, 0x1023508}, check_handles = {0x1023518, 0x1023518}, idle_handles = {0x1023528, 0x1023528}, async_handles = {0x10234d8, 0x101f708}, async_watcher = {cb = 0x7299e0 <uv__async_event>, io_watcher = {
      cb = 0x729ad0 <uv__async_io>, pending_queue = {0x1023558, 0x1023558}, watcher_queue = {0x1023568, 0x1023568}, pevents = 1, events = 1, fd = 9}, wfd = -1}, timer_handles = {rbh_root = 0x2ae8340}, time = 440397716, signal_pipefd = {7, 8}, signal_io_watcher = {
    cb = 0x72ff70 <uv__signal_event>, pending_queue = {0x10235b0, 0x10235b0}, watcher_queue = {0x10235c0, 0x10235c0}, pevents = 1, events = 1, fd = 7}, child_watcher = {close_cb = 0, data = 0x0, loop = 0x10233e0, type = UV_SIGNAL, handle_queue = {0x10234b0, 0x10233f0},
    flags = 32768, next_closing = 0x0, signal_cb = 0, signum = 0, tree_entry = {rbe_left = 0x0, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0, dispatched_signals = 0}, emfile_fd = 10, timer_counter = 66, inotify_read_watcher = {cb = 0,
    pending_queue = {0x0, 0x0}, watcher_queue = {0x0, 0x0}, pevents = 0, events = 0, fd = 0}, inotify_watchers = 0x0, inotify_fd = -1}
(gdb) x req->active_queue[0]
0x2b1b188:      0x02b1b188
(gdb) x req->active_queue[1]
0x100000001:    Cannot access memory at address 0x100000001
```

``` c
#define uv__req_unregister(loop, req)                                         \
  do {                                                                        \
    assert(uv__has_active_reqs(loop));                                        \
    QUEUE_REMOVE(&(req)->active_queue);                                       \
  }                                                                           \
  while (0)
```

My interpretation is that `req->active_queue[0]` is `next` and `req->active_queue[1]` is `prev`. `QUEUE_REMOVE()` tries to access `next` of `prev`, resulting in an invalid memory access due to `prev` being 0x100000001. How can this happen? The stack trace does not shed much light on what is causing this problem to appear in the first place, all it mentions is node startup and libuv. Does the root of the problem lie in my code, an addon, node.js or libuv?

**Comment by indutny** [comment] 2013-12-12 21:59
@kkoopa Thanks for opening, I'll look into it soon. (or @saghul if you'll have time).

**Comment by saghul** [comment] 2013-12-30 09:36
Looks like that req has been partially overwritten or something, by looking at the addresses of its members, and the type.

It's hard to tell where the problem might be, but I'd bet it's not on libuv or it would have bitten us by now :-) Node itself or an addon using libuv directly could be the culprits, but you'll need to isolate the problem by removing addons until you find the source of the problem.

**Comment by indutny** [comment] 2013-12-31 09:54
@kkoopa sorry for a big delay, are you using any C++ addon with node? Do you have a test case that is most likely reproducing this issue?

**Comment by saghul** [comment] 2014-02-18 13:15
No follow up, closing. If you find the root cause, please attach a C test which trigger is so we can fix it, thanks!

**Closed as completed by saghul** 2014-02-18 13:15 UTC
