### ISSUE TITLE
Setting `process.title` causes the process to show up as "Not Responding" in OS X's Activity Monitor, in Mavericks

### ISSUE THREAD

**Issue by TooTallNate** [joyent/libuv#966] opened 2013-10-23 19:08 UTC
It takes a few minutes to trigger, but eventually the process shows up red and is marked as "Not Responding", even though the process itself is running normal.

[![](https://cloudup.com/cIKf2lX9DNQ+)](https://cloudup.com/cIKf2lX9DNQ)

My initial guess is that the trick we do in order to set the process title ends up making Activity Monitor think that the process is a GUI app, rather than a command line app, and then it's expecting some kind of ACK from the Cocoa event loop at that point which never happens.

**Comment by indutny** [comment] 2013-10-28 10:30
Hm... @TooTallNate, I've seen this happening with other applications since update to 10.9. Perhaps, its not related to node/libuv at all? Also, I wasn't able to reproduce it locally.

**Comment by indutny** [comment] 2013-10-28 10:31
Oh, wait... confirming it.

**Comment by indutny** [comment] 2013-10-28 13:35
Should be fixed by https://github.com/joyent/libuv/pull/973, needs backporting to v0.10.

**Closed as completed** 2013-10-28 16:59 UTC
Labels: Darwin

**Comment by indutny** [comment] 2013-10-28 17:01
Fixed!
