### ISSUE TITLE
uv_udp_start_recv callback with nread = 0

### ISSUE THREAD

**Issue by txdv** [joyent/libuv#1349] opened 2014-07-02 12:48 UTC
UDP packets can be sent with 0 content.
The content of the UDP packet is literally nothing, we are just sending the udp header.

Now look at the callback:

``` c
typedef void (*uv_udp_recv_cb)(uv_udp_t* handle, ssize_t nread,  const uv_buf_t* buf, const struct sockaddr* addr, unsigned flags);
```

In the case of an empty udp packets we have nread == 0 and addr != NULL

When the udp handle is closed it also issues a callback with nread == 0 and addr == NULL.

This is bad API design. Users of libuv will forget to check for addr. It is already a [bug in nodejs](https://github.com/joyent/node/issues/7884). You can't currently receive empty udp packets. 

I propose to drop the callback with 0 on socket closing. Maybe add another callback in the fields.

**Comment by saghul** [comment] 2014-07-02 13:50
Thanks for the report Andrius, will investigate.

**Comment by txdv** [comment] 2014-07-02 14:10
At least it should be documented...

**Comment by txdv** [comment] 2014-07-02 14:42
https://github.com/joyent/libuv/pull/1350

here is the pull request for documentation

**Comment by saghul** [comment] 2014-07-02 16:58
For completeness, it's like this by design. #1350 landed enhancing documentation, thanks!

**Closed as completed by saghul** 2014-07-02 16:58 UTC
