### ISSUE TITLE
uv_shutdown callback would not trigger when client network card disable.

### ISSUE THREAD

**Issue by dawnarc** [joyent/libuv#995] opened 2013-11-18 06:43 UTC
when a client connect to server success, then disable network card, server was keeping the connection, now if server invoke the uv_shutdown function to close the unavailable socket, uv_shutdown callback function would not trigger, thus the uv_shutdown_t *req can't be free memory.

**Comment by dawnarc** [comment] 2013-11-18 06:45
the version of libuv I used is 0.10.13

**Comment by bnoordhuis** [comment] 2013-11-18 08:45
That sounds highly implausible.  On what operating system is that?  Can you maybe post your code or a test case?

**Comment by dawnarc** [comment] 2013-11-18 12:07
this case can be reappear both on windows server 2003 and windows server 2008, I think it isn't related to platform. in my project, each client side would send a heart package to server side in every 10 seconds, if server didn't receive heart package from a client after 30 seconds, then server would close this client initiative.

``` c++
void Client::CloseClient()
{
    LOG_ERROR("333333333 " << m_Index << " " << m_IsFree << " " << m_Tick);
    uv_shutdown_t* req = (uv_shutdown_t*) malloc(sizeof *req);
    req->data = this;
    uv_shutdown(req, (uv_stream_t*)m_tcp_client, Client::after_shutdown);
}

void Client::after_shutdown(uv_shutdown_t* req, int status)
{
    //clean data
    Client *cli = (Client*)req->data;
    LOG_ERROR("44444 " << cli->m_Index << " " << cli->m_IsFree << " " << cli->m_Tick);

    uv_mutex_lock(&cli->m_mutex);
    cli->m_IsFree = true;
    cli->m_Tick = 0;
    uv_mutex_unlock(&cli->m_mutex);

    cli->m_RecvBuf->Reset();
    cli->m_SendBuf->Reset();
    cli->m_SendQueue.Reset();

    uv_close((uv_handle_t*)req->handle, on_close);
    free(req);
}
```

if I close client side program normal, my program would print "3333" and "4444", but when I disable client side network card, and 30 seconds past, my program print "3333" only.

**Comment by dawnarc** [comment] 2013-11-18 12:20
the github coment editor remove point sign(asterisk) in my code, I repost my code:
Client *cli = (Client *) req->data;

**Comment by piscisaureus** [comment] 2013-11-18 15:23
Can you check the return value of uv_shutdown?

I think it's returning UV_ECONNRESET or UV_ECONNABORTED.

Not you will argue that this error should not be returned, but passed to the callback instead.
I agree.
But I have no time for fixing this atm so you'll have to deal with this for now, or send a patch.

**Comment by dawnarc** [comment] 2013-11-26 14:41
unfortunately, uv_shutdown didn't return errno, it return 0. if I invoke uv_shutdown again, it return -1;

**Comment by saghul** [comment] 2014-03-10 20:26
No follow up, tentatively closing since it couldn't be reproduced. If it still happens to you with latest libuv please create a C test case demonstrating the problem so we can try to track it down.

**Closed as completed by saghul** 2014-03-10 20:26 UTC
